export const products = [
  {
    FirstName: 'John',
    LastName: 'Doe',
    ProductName: 'Task A',
    UnitPrice: 100,
    Discontinued: false,
    UnitsInStock: 10,
    AssignedDate: '2025-04-01',
    SalesRep: 'Jane Smith',
    Coordinator: 'Mark Wilson',
    SyncToMobile: true,
    CreatedSource: 'CRM',
    PrimaryEmail: 'john.doe@example.com',
    PrimaryPhone: '123-456-7890',
    LMPLLeadID: 'A12345',
    AppointmentType: 'Meeting',
    BookingAgency: 'Agency X'
  },
  {
    FirstName: 'Alice',
    LastName: 'Johnson',
    ProductName: 'Task B',
    UnitPrice: 150,
    Discontinued: false,
    UnitsInStock: 20,
    AssignedDate: '2025-03-20',
    SalesRep: 'Michael Brown',
    Coordinator: 'Sarah Lee',
    SyncToMobile: false,
    CreatedSource: 'Website',
    PrimaryEmail: 'alice.johnson@example.com',
    PrimaryPhone: '234-567-8901',
    LMPLLeadID: 'B23456',
    AppointmentType: 'Follow-up',
    BookingAgency: 'Agency Y'
  },
  {
    FirstName: 'Bob',
    LastName: 'Williams',
    ProductName: 'Task C',
    UnitPrice: 200,
    Discontinued: true,
    UnitsInStock: 0,
    AssignedDate: '2025-02-15',
    SalesRep: 'Emily Davis',
    Coordinator: 'David Evans',
    SyncToMobile: true,
    CreatedSource: 'Referral',
    PrimaryEmail: 'bob.williams@example.com',
    PrimaryPhone: '345-678-9012',
    LMPLLeadID: 'C34567',
    AppointmentType: 'Meeting',
    BookingAgency: 'Agency Z'
  }
];