export const products = [
  {
    ProductID: 101,
    ProductName: "Chai",
    FirstName: "John",
    LastName: "Doe",
    QuantityPerUnit: "10 boxes x 20 bags",
    UnitPrice: 100,
    UnitsInStock: 10,
    UnitsOnOrder: 5,
    ReorderLevel: 10,
    FirstOrderedOn: new Date(2025, 3, 1),
    AssignedDate: "2025-04-01",
    SalesRep: "Jane Smith",
    Coordinator: "Mark Wilson",
    CreatedSource: "CRM",
    PrimaryEmail: "john.doe@example.com",
    PrimaryPhone: "123-456-7890",
    LMPLLeadID: "A12345",
    AppointmentType: "Meeting",
    BookingAgency: "Agency X",
    Category: "Cake"
  },
  {
    ProductID: 102,
    ProductName: "Task B",
    FirstName: "Alice",
    LastName: "Johnson",
    QuantityPerUnit: "5 packs x 15 items",
    UnitPrice: 150,
    UnitsInStock: 20,
    UnitsOnOrder: 2,
    ReorderLevel: 5,
    FirstOrderedOn: new Date(2025, 2, 20),
    AssignedDate: "2025-03-20",
    SalesRep: "Michael Brown",
    Coordinator: "Sarah Lee",
    CreatedSource: "Website",
    PrimaryEmail: "alice.johnson@example.com",
    PrimaryPhone: "234-567-8901",
    LMPLLeadID: "B23456",
    AppointmentType: "Follow-up",
    BookingAgency: "Agency Y",
    Category: "Cake"
  },
  {
    ProductID: 103,
    ProductName: "Green Tea",
    FirstName: "Sarah",
    LastName: "White",
    QuantityPerUnit: "12 boxes x 25 bags",
    UnitPrice: 120,
    UnitsInStock: 30,
    UnitsOnOrder: 3,
    ReorderLevel: 10,
    FirstOrderedOn: new Date(2025, 1, 15),
    AssignedDate: "2025-02-10",
    SalesRep: "Emily Clark",
    Coordinator: "Jason Taylor",
    CreatedSource: "Retail",
    PrimaryEmail: "sarah.white@example.com",
    PrimaryPhone: "345-678-9012",
    LMPLLeadID: "C34567",
    AppointmentType: "Product Launch",
    BookingAgency: "Agency Z",
    Category: "Cake"
  },
  {
    ProductID: 104,
    ProductName: "Office Chair",
    FirstName: "Michael",
    LastName: "Green",
    QuantityPerUnit: "1 unit",
    UnitPrice: 300,
    UnitsInStock: 15,
    UnitsOnOrder: 0,
    ReorderLevel: 5,
    FirstOrderedOn: new Date(2025, 3, 5),
    AssignedDate: "2025-04-05",
    SalesRep: "William Scott",
    Coordinator: "Linda Davis",
    CreatedSource: "Retail",
    PrimaryEmail: "michael.green@example.com",
    PrimaryPhone: "456-789-0123",
    LMPLLeadID: "D45678",
    AppointmentType: "Delivery",
    BookingAgency: "Agency X",
    Category: "iceCream"
  },
  {
    ProductID: 105,
    ProductName: "Laptop",
    FirstName: "David",
    LastName: "Harris",
    QuantityPerUnit: "1 unit",
    UnitPrice: 1200,
    UnitsInStock: 8,
    UnitsOnOrder: 4,
    ReorderLevel: 3,
    FirstOrderedOn: new Date(2025, 0, 10),
    AssignedDate: "2025-01-15",
    SalesRep: "Olivia Martinez",
    Coordinator: "Sophia Lewis",
    CreatedSource: "Website",
    PrimaryEmail: "david.harris@example.com",
    PrimaryPhone: "567-890-1234",
    LMPLLeadID: "E56789",
    AppointmentType: "Consultation",
    BookingAgency: "Agency Y",
    Category: "Cake"
  }
];
